import java.util.Scanner;
public class ExIF {
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);

        // 1. FAÇA UM PROGRAMA QUE MOSTRE SE O ALUNO FOI APROVADO OU REPROVADO CONSIDERANDO A MEDIA DE DUAS NOTAS

        // 2. FAÇA UM PROGRAMA QUE DADO O SALARIO DE UMA PESSOA, VERIFIQUE SE PODE SER REALIZADO UM EMPRESTIMO (VALOR E QUANTIDADE DE PARCELAS). CONSIDERE QUEO EMPRESTIMO SÓ PODE SER CONCEDIDO CASO O VALOR DA PARCELA SEJA MENOR DO QUE 30% DO SALÁRIO

        // 3. FAÇA UM PROGRAMA QUE RECEBA 2 VALORES X, Y E GARANTA QUE AO FINAL, X SEJA MENOR QUE Y (TROCANDO OS VALORES SE NECESSARIO)




    }
}